"""person table

Revision ID: 0e4beb68dec2
Revises: 
Create Date: 2020-11-21 02:21:44.582720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e4beb68dec2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('street', sa.String(length=32), nullable=True),
    sa.Column('number', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_city'), 'person', ['city'], unique=False)
    op.create_index(op.f('ix_person_country'), 'person', ['country'], unique=False)
    op.create_index(op.f('ix_person_first_name'), 'person', ['first_name'], unique=False)
    op.create_index(op.f('ix_person_last_name'), 'person', ['last_name'], unique=False)
    op.create_index(op.f('ix_person_number'), 'person', ['number'], unique=False)
    op.create_index(op.f('ix_person_street'), 'person', ['street'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_street'), table_name='person')
    op.drop_index(op.f('ix_person_number'), table_name='person')
    op.drop_index(op.f('ix_person_last_name'), table_name='person')
    op.drop_index(op.f('ix_person_first_name'), table_name='person')
    op.drop_index(op.f('ix_person_country'), table_name='person')
    op.drop_index(op.f('ix_person_city'), table_name='person')
    op.drop_table('person')
    # ### end Alembic commands ###
